### ISSUE TITLE
Use of this plugin causes scene `update` to get called 2 times before create on `restart()`

### ISSUE THREAD

**Issue by sean256** [Osmose/phaser-tiled-json-external-loader#2]
Phaser 3.17.0

Description:

I was having this crazy bug where if I restarted my scene (or went to scene b then back to a) it would crash in my update method for undefined items. After some digging I found that my scene was having `update` called BEFORE `create` but only after the scene had been loaded at least once.

I removed all of my code until I found the culprit.

`this.load.tilemapTiledJSONExternal('map', '/assets/level1.json');` in my preload method.

```
class SceneLevel extends Phaser.Scene {
	constructor() {
		super({ key: 'SceneLevel' });
	}
	preload({ level = 1 } = {}) {
		console.log('preload');
		this.load.tilemapTiledJSONExternal('map', '/assets/level1.json');
	}
	update() {
		console.log('update');
	}
	create() {
		console.log('create');
		this.time.delayedCall(3000, () => this.scene.restart());
	}
}
```

outputs to console

```
[Log] preload
[Log] create
[Log] update (x184)
[Log] preload
[Log] update (x2) // here it is. Why does this plugin cause this to be called here?
[Log] create
```

**Comment by Osmose** [comment]
Thanks for the issue, I'll see if I can replicate/diagnose this hopefully sometime this weekend.

**Comment by Osmose** [comment]
Okay, I tracked this down. Details are here: https://github.com/photonstorm/phaser/issues/4629

IMO this is a Phaser-side issue (unless the devs get back and say it's my plugin's fault for a reason I don't currently know), so there's nothing to fix on our side. In the meantime, the workaround is to add a check at the start of your `update` method to abort running if the scene isn't active:

```js
if (!this.sys.isActive()) {
  return;
}
```

Hope that helps!

**Comment by visuallization** [comment]
I am experiencing the same thing with phaser's internal `multiatlas`. So if my setup is not completely messed up, it is quiet likely on phaser's side.
